### PR TITLE
lombokify the model-library to avoid boilerplate code

### PR DESCRIPTION
**Pull request by berndhopp**
[lombok](https://projectlombok.org/) is an annotation-generator library for java that aims to reduce code-size by generating boilerplate code like getters/setters, constructors and so forth. This PR brings the code-size down ca 150 lines by auto-generating accessors and removing one unused class.

### CODE REVIEW

**Comment by dcremonini** [comment]
Lombok advantages:
code is 

- shorter

Lombok disadvantages:

- annotations bring in semantic while they should not
- stacking its annotations on others reduce readability
- Since it's not part of the official language, ofter IDE support is delayed
- Debugging is more cumbersome
- Not every developer knows Lombok
- In a future, if delomboking will be decided, the resulting code might not give the expected results.

I paste here some links to articles and discussions because Lombok doesn't worth it:
https://stackoverflow.com/questions/3852091/is-it-safe-to-use-project-lombok
https://stackoverflow.com/questions/4589184/what-are-the-risks-with-project-lombok
https://artofcode.wordpress.com/2018/12/18/dont-use-lombok/
https://medium.com/@ppbruna/why-you-should-not-use-lombok-f7556662e8c3

Does the project really need Lombo?k?
I don't think so
My 2 cents

**Comment by berndhopp** [comment]
I don't think any of these arguments is factual, except that not every dev knows Lombok, which is btw true for absolutely every Java api.

**Comment by dcremonini** [comment]
Which argument do you think is not factual?

**Comment by berndhopp** [comment]
annotations bring in semantic while they should not
-> who says they should not? EJB-frameworks like jpa and others use annotations in that way and annotation processing is part of the Java standard. 

stacking its annotations on others reduce readability
-> why would that reduce readability? Using Lombok may be a matter of taste, but repetitive getters and setters just can't be sold as an improvement in terms of readability. 

Since it's not part of the official language, ofter IDE support is delayed
-> support for intellij and eclipse is reliable, easy and stable for years now

Debugging is more cumbersome
-> not in my experience. but for people that don't know what Lombok does, it may be confusing for a little while. Then again, software development brings with it that you need to learn new frameworks constantly and Lombok is pretty much self explanatory. 

In a future, if delomboking will be decided, the resulting code might not give the expected results.

-> the delombok maven target simply writes the otherwise invisible generated code into the Java files, which is exactly the expected result. Delombok does not change the bytecode one bit.

**Comment by dcremonini** [comment]
Hello,

thank you for replying.

Here are the facts.

**annotations bring in semantic while they should not**
-> who says they should not? EJB-frameworks like jpa and others use annotations in that way and annotation processing is part of the Java standard.

--> It's clearly stated in the JSR 175: A Metadata Facility for the JavaTM Programming Language
Then the tools was distorted the same way like a hammer can be used to hit a screw instead of using a screwdriver.
Just because something exists, it doesn't mean it's well done. EJB before version 3 were a freak of computer science and GregorianCalendar has been waiting for about 15 years before some cleaning was made.

**stacking its annotations on others reduce readability**
-> why would that reduce readability? Using Lombok may be a matter of taste, but repetitive getters and setters just can't be sold as an improvement in terms of readability.

--> I'm not trying to sell getters and setters as an improvement in terms of readability but do not I try to sell that stripping them is a improvement either. What I say is that behaviour cannot be understood just watching the code, you have to read elsewhere

**Since it's not part of the official language, ofter IDE support is delayed**
-> support for intellij and eclipse is reliable, easy and stable for years now

--> Actually the support is always delayed, even though maybe for a couple of weeks is just annoying. As a matter of fact it is maybe easy as you say but surely not that reliable and stable. In my experience interactions with IDE entail a lot of unnecessary cleaning of the target just because of a mysterious bug dissolved by rebuilding. Also there in the Lombok project there as as of 03/05/2020 counts 612 issues and tens of them are bug related to IDE and other tens to problems while compiling.

**Debugging is more cumbersome**
-> not in my experience. but for people that don't know what Lombok does, it may be confusing for a little while. Then again, software development brings with it that you need to learn new frameworks constantly and Lombok is pretty much self explanatory.

--> Today 03/05/2020 using Idea 2020.1.1 and the Michail Plushnikov lombok plugin (maybe you have a plugin better than this one) I tried once again to used Lombok.

Here is my experience:	
- Debug step into ==> Error message: "Source code doesn't match the bytecode" (good luck if you want to debug equals and hashCode methods)
- @AllArgsConstructor and @NoArgsConstructor the IntelliJ Find usages command is not able to find usages and trying the same from the generated code doesn't work either
- @Synchronized cannot be delomboked, I found no generated code, it's impossible to debug


**In a future, if delomboking will be decided, the resulting code might not give the expected results.**

-> the delombok maven target simply writes the otherwise invisible generated code into the Java files, which is exactly the expected result. Delombok does not change the bytecode one bit.

--> Maven delomboking doesn't work out of the box. Applicating the instructions given in the plugin home page I obtain an error (missing mandatory parameter, so supplementary work and troubleshooting is needed). The IntelliJ delombok option doesn't delombok all the stuff.

This discussion is not about fundamentalism, is about something that looks promising but all the way long involves more lost time that advantages.

Daniele

**Comment by martinalig** [comment]
Hi

Thanks for the inputs, the interesting discussion and the pros and cons for using lombok.

At the moment we decided not to integrate lombok, mainly because the project only has very few models and the benefit is not that big.

**Pull request closed without merging**
