### PR TITLE
Trivial: add maven-enforcer-plugin to require the right Java version

### PR DESCRIPTION
**Pull request by bdelacretaz**

### CODE REVIEW

**Comment by martinalig** [comment]
Any comments why you would like to include this plugin?

**Comment by bdelacretaz** [comment]
It allows for failing the build early if the JVM is not the right version, with a clear error message, here's what you get with my PR:

    $ java -version
    java version "1.8.0_171"
    ...
    $ mvn -o compile
     ....
    [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-versions) @ dpppt-backend-sdk ---
    [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
    Detected JDK Version: 1.8.0-171 is not in the allowed range 11.
    ...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    ....

Another useful thing might be to enforce a specific Maven version range with `requireMavenVersion`, see http://maven.apache.org/enforcer/maven-enforcer-plugin/usage.html

I think such checks avoid surprises when others try building with "unexpected" versions of their tools.

**Comment by ubamrein** [comment]
We are already using the toolchains plugin (https://maven.apache.org/guides/mini/guide-using-toolchains.html) to force the configuration of the correct JDK. I think one of them would be enough, but I don't have strong feelings on which is better. 

The advantage of the maven-enfoorcer-plugin is that it does not need any further configuration.
 
The toolchains plugin on the other hand would allow to configure whatever you like without much hazzle (e.g. a JDK which for some reason does not match the version string, but still produces correct byte code).

**Comment by bdelacretaz** [comment]
In "my" projects we use the enforcer plugin to avoid surprises when someone or some CI/CD system runs `mvn clean install`, whatever their local configuration is (Maven and JVM versions in particular) and also ban outdated Maven plugins, see examples at [1] and [2]. Those examples are from Apache Sling which groups more than 300 Git repositories, so we need some solid "consistency management" and the enforcer helps with that.

Feel free to ignore this is you have other mechanisms that work for you, I meant this PR just as a suggestion!

[1] https://github.com/apache/sling-parent/blob/47b700f123098de9b77d8b746b2b2d9b211ca0c8/sling-bundle-parent/pom.xml#L120

[2] https://github.com/apache/sling-parent/blob/47b700f123098de9b77d8b746b2b2d9b211ca0c8/sling-bundle-parent/pom.xml#L119

**Comment by ubamrein** [comment]
This way is much easier to handle CIs! Thanks for the suggestion :)

**Pull request merged**
