### PR TITLE
Maven dependency and plugin management optimisation

### PR DESCRIPTION
**Pull request by iCesofT**
Hi,

I create this PR to get better Maven configuration with dependency and plugin managements.

You can close PR # 143 that I did some time ago.

Kind regards

### CODE REVIEW

**Comment by ineiti** [comment]
Java-newbie here: why are you adding these dependencies, while they were not in the original pom-file?

**Comment by iCesofT** [comment]
They aren't in original pom file but are dependencies from spring:
- snakeyaml -> you use "spring-boot-starter" so it uses that library.
- postgresql -> you have it in "dpppt-backend-sdk-data/pom.xml" (if you have a parent pom, you should manage dependency and plugin versions from parent).
- tomcat -> spring-boot-starter-web from dpppt-backend-sdk-ws/pom.xml.

And if you compile from command-line, you get some Maven warnings regarding missing versions  ("build.plugins.plugin.version") or duplicate declaration of plugin (jacoco-maven-plugin):
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.

**Comment by ineiti** [comment]
OK - sounds good. Can you look how to get the build running again?

**Comment by iCesofT** [comment]
It's strange. Maven compiles but in remote Sonar it doesn't :?

**Comment by jopereira** [comment]
> It's strange. Maven compiles but in remote Sonar it doesn't :?

This might be a sonar bug with pull requests from forked repos. See for instance: https://github.com/corona-warn-app/cwa-server/issues/237

**Comment by martinalig** [comment]
@iCesofT Thanks for your inputs.
Can we not just upgrade to Spring Boot 2.3.4.RELEASE ? By doing so, the above dependenciees are also updated. Spring Boot does a good job in maintaining up to date dependencies, so I think if possible, it easier to just go with the latest Spring Boot version. 
What do you think?

**Comment by iCesofT** [comment]
I didn't check it. I tried before with 2.3.X and it didn't pass tests 🧐

**Comment by iCesofT** [comment]
I already checked it. It doesn't pass tests with 2.3.4 but works with 2.2.10 and fixes the issues.

**Comment by iCesofT** [comment]
I will create a new pull request with Spring Boot 2.2.10 so I close this PR.

**Pull request closed without merging**
